CREATE TABLE [dbo].[USER_LOGIN] (
    [USER_ID]       INT          IDENTITY (1, 1) NOT NULL,
    [NOME_USER]     VARCHAR (255) NOT NULL,
    [DEPARTMENT_ID] INT           NOT NULL,
    [EMAIL]         VARCHAR (255) NOT NULL,
    [USER_PASSWORD] VARCHAR (255) NOT NULL,
    [DATE_CREATE]   DATETIME      NOT NULL,
    [DATE_MODIFIED] DATETIME      NOT NULL,
    CONSTRAINT [FK_USER_LOGIN_X_DEPARTMENT] FOREIGN KEY ([DEPARTMENT_ID]) REFERENCES [DEPARTMENT](DEPARTMENT_ID),
    PRIMARY KEY CLUSTERED ([USER_ID] ASC)
);

