CREATE TABLE [dbo].[USER_LOGIN] (
    [USER_ID]       INT          IDENTITY (1, 1) NOT NULL,
    [NOME_USER]     VARCHAR (255) NOT NULL,
    [DEPARTMENT]    VARCHAR (255) NOT NULL,
    [EMAIL]         VARCHAR (255) NOT NULL,
    [USER_PASSWORD] VARCHAR (255) NOT NULL,
    [DATE_CREATE]   DATETIME      NOT NULL,
    [DATE_MODIFIED] DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([USER_ID] ASC)
);

