CREATE TABLE [dbo].[USER_LOGIN] (
    [USER_ID]       INT           NOT NULL,
    [NOME_USER]     VARCHAR (255) NOT NULL,
    [DEPARTMENT]    VARCHAR (255) NOT NULL,
    [EMAIL]         VARCHAR (255) NOT NULL,
    [USER_PASSWORD] VARCHAR (255) COLLATE Latin1_General_BIN2  ENCRYPTED WITH (
     COLUMN_ENCRYPTION_KEY = [CEK_Auto1],
     ALGORITHM = N'AEAD_AES_256_CBC_HMAC_SHA_256',
     ENCRYPTION_TYPE = RANDOMIZED
    ) NOT NULL,
    [DATE_CREATE]   DATETIME      NOT NULL,
    [DATE_MODIFIED] DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([USER_ID] ASC)
);

